spring:
  application:
    name: E-Gate-2.0
  data:
    mongodb:
#      host: host.docker.internal
      host: localhost
      port: 27017
      database: e-gate
  banner:
    location: E-Gate_v2.0-Banner.txt
  mail:
    host: smtp.gmail.com
    port: 587
    username: kce.egate@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
server:
  port: 8080
jwt:
  secret : 843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
  expiration : 3600000